version: '3'

services:
    zabbix-server:
        image: zabbix/zabbix-server-mysql:latest
        container_name: zabbix-server
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /docker/data/zabbix/server:/var/lib/zabbix
        networks:
            - agents
            - zabbix_mysqls
        ports:
            - 10051:10051
        environment:
            DB_SERVER_HOST: 'mysql'
            MYSQL_DATABASE: 'zabbix'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'mysql123'
            MYSQL_ROOT_PASSWORD: 'mysql123'
            PHP_TZ: "Asia/Shanghai"

    zabbix-web:
        depends_on:
            - zabbix-server
        image: zabbix/zabbix-web-nginx-mysql:latest
        networks:
            - zabbix_mysqls
        container_name: zabbix-web
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        ports:
            - 8080:80
        environment:
            DB_SERVER_HOST: 'mysql'
            MYSQL_DATABASE: 'zabbix'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'mysql123'
            MYSQL_ROOT_PASSWORD: 'mysql123'
            PHP_TZ: "Asia/Shanghai"

    zabbix-agent:
        depends_on:
            - zabbix-server
        image: zabbix/zabbix-agent:latest
        networks:
            - agents
        container_name: zabbix-agent
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /docker/data/zabbix/server:/var/lib/zabbix
        privileged: true
        ports:
            - 10050:10050
        environment:
            ZBX_HOSTNAME: 'Zabbix server'
            ZBX_SERVER_HOST: 'zabbix-server'

networks:
    agents:
    zabbix_mysqls:
        external: true
